services:
  - type: web
    name: rivr-api-dev
    env: node
    plan: free
    branch: develop
    autoDeploy: false
    healthCheckPath: /api/auth/health
    buildCommand: >-
      bash -lc "corepack enable && corepack prepare pnpm@8.15.6 --activate && pnpm install --frozen-lockfile && pnpm --filter ./packages/logger --filter ./packages/schema --filter ./apps/api build"
    startCommand: node apps/api/dist/index.js
    postDeployCommand: >-
      bash -lc "corepack enable && corepack prepare pnpm@8.15.6 --activate && pnpm --filter ./apps/api db:push && pnpm --filter ./apps/api seed:full"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: development
      - key: BASE_DOMAIN
        value: rivr-api-dev.onrender.com
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false

  - type: web
    name: rivr-api-prod
    env: node
    plan: free
    branch: main
    autoDeploy: false
    healthCheckPath: /api/auth/health
    buildCommand: >-
      bash -lc "corepack enable && corepack prepare pnpm@8.15.6 --activate && pnpm install --frozen-lockfile && pnpm --filter ./packages/logger --filter ./packages/schema --filter ./apps/api build"
    startCommand: node apps/api/dist/index.js
    postDeployCommand: >-
      bash -lc "corepack enable && corepack prepare pnpm@8.15.6 --activate && pnpm --filter ./apps/api db:push"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: BASE_DOMAIN
        value: rivr-api-prod.onrender.com
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false

  - type: web
    name: rivr-web-dev
    env: node
    plan: free
    branch: develop
    autoDeploy: false
    rootDir: apps/app
    buildCommand: >-
      bash -lc "corepack enable && corepack prepare pnpm@8.15.6 --activate && pnpm -w install --frozen-lockfile && pnpm --filter ./packages/logger --filter ./packages/schema --filter ./packages/ui build && pnpm build"
    startCommand: bash -lc "pnpm start -- -p $PORT"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: development
      - key: NEXT_PUBLIC_BASE_DOMAIN
        value: rivr-api-dev.onrender.com
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://rivr-api-dev.onrender.com
      - key: NEXT_PUBLIC_WS_URL
        value: wss://rivr-api-dev.onrender.com/ws

  - type: web
    name: rivr-web-prod
    env: node
    plan: free
    branch: main
    autoDeploy: false
    rootDir: apps/app
    buildCommand: >-
      bash -lc "corepack enable && corepack prepare pnpm@8.15.6 --activate && pnpm -w install --frozen-lockfile && pnpm --filter ./packages/logger --filter ./packages/schema --filter ./packages/ui build && pnpm build"
    startCommand: bash -lc "pnpm start -- -p $PORT"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BASE_DOMAIN
        value: rivr-api-prod.onrender.com
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://rivr-api-prod.onrender.com
      - key: NEXT_PUBLIC_WS_URL
        value: wss://rivr-api-prod.onrender.com/ws
