name: Deploy API to Render

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch: {}

concurrency:
  group: render-api-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build & Test API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable pnpm
        run: corepack enable && corepack prepare pnpm@8.15.6 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build workspace packages and API
        run: pnpm --filter ./packages/logger --filter ./packages/schema --filter ./apps/api build

  deploy-dev:
    name: Deploy Dev
    needs: build-test
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy (dev)
        run: curl -sSf -X POST "${{ secrets.RENDER_DEV_HOOK_URL }}"

  deploy-prod:
    name: Deploy Prod
    needs: build-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy (prod)
        run: curl -sSf -X POST "${{ secrets.RENDER_PROD_HOOK_URL }}"
